### ISSUE TITLE
Numeric hotkey causes crash 

### ISSUE THREAD

**Issue by Vzor-** [EnderWiggin/Custom-Salem#11]
It happens every time. I am using a standard ANSI keyboard. 

java.lang.RuntimeException: java.lang.NullPointerException
	at com.jogamp.common.util.awt.AWTEDTExecutor.invoke(AWTEDTExecutor.java:58)
	at jogamp.opengl.awt.AWTThreadingPlugin.invokeOnOpenGLThread(AWTThreadingPlugin.java:103)
	at jogamp.opengl.ThreadingImpl.invokeOnOpenGLThread(ThreadingImpl.java:206)
	at javax.media.opengl.Threading.invokeOnOpenGLThread(Threading.java:172)
	at javax.media.opengl.Threading.invoke(Threading.java:191)
	at javax.media.opengl.awt.GLCanvas.display(GLCanvas.java:528)
	at haven.HavenPanel.uglyjoglhack(HavenPanel.java:418)
	at haven.HavenPanel.run(HavenPanel.java:451)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at haven.GameUI.checkBelt(GameUI.java:710)
	at haven.GameUI.wdgmsg(GameUI.java:704)
	at haven.ToolBeltWdg$5.hit(ToolBeltWdg.java:308)
	at haven.MapView$Hittest.run(MapView.java:1101)
	at haven.MapView.undelay(MapView.java:839)
	at haven.MapView.draw(MapView.java:931)
	at haven.Widget.draw(Widget.java:514)
	at haven.Widget.draw(Widget.java:519)
	at haven.GameUI.draw(GameUI.java:574)
	at haven.Widget.draw(Widget.java:514)
	at haven.Widget.draw(Widget.java:519)
	at haven.RootWidget.draw(RootWidget.java:84)
	at haven.UI.draw(UI.java:162)
	at haven.HavenPanel.redraw(HavenPanel.java:296)
	at haven.HavenPanel$1.display(HavenPanel.java:92)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:649)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:633)
	at javax.media.opengl.awt.GLCanvas$9.run(GLCanvas.java:1271)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1103)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:978)
	at javax.media.opengl.awt.GLCanvas$10.run(GLCanvas.java:1282)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by EnderWiggin** [comment]
fixed by properly checking if belt has action mapped before checking whether to open craft menu for this action.
